sonar.projectKey=fitforge-workout-service
sonar.projectName=fitforge-workout-service

# where the code is inside this service
sonar.sources=src

# ignore junk
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/*.test.js

sonar.sourceEncoding=UTF-8